// - LOGIN
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_START = 'LOGIN_START';

// - LOGOUT
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
export const LOGOUT_START = 'LOGOUT_START';

// - REGISTER
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REGISTER_START = 'REGISTER_START';
export const SAVE_PROFILE_IMAGE = 'SAVE_PROFILE_IMAGE';
export const SAVE_PROFILE_NAME = 'SAVE_PROFILE_NAME';

// - ADDRESS
export const REGISTER_ADDRESS = 'REGISTER_ADDRESS';
export const SAVE_ADDRESS = 'SAVE_ADDRESS';
export const SET_ACTIVE_ADDRESS = 'SET_ACTIVE_ADDRESS';

// - CART
export const ADD_TO_CART = 'ADD_TO_CART';
export const SET_PARTNER = 'SET_PARTNER';
export const CLEAR_PARTNER = 'CLEAR_PARTNER';
export const SET_CART = 'SET_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const ADD_TOTALPRICE = 'ADD_TOTALPRICE';
export const MINUS_TOTALPRICE = 'MINUS_TOTALPRICE';
export const CLEAR_TOTALPRICE = 'CLEAR_TOTALPRICE';
export const SAVE_TOTALPRICE = 'SAVE_TOTALPRICE';
export const ADD_DISCOUNTPRICE = 'ADD_DISCOUNTPRICE';
export const MINUS_DISCOUNTPRICE = 'MINUS_DISCOUNTPRICE';
export const CLEAR_DISCOUNTPRICE = 'CLEAR_DISCOUNTPRICE';
export const SAVE_DISCOUNTPRICE = 'SAVE_DISCOUNTPRICE';

// - USER
export const SAVE_USER_DATA = 'SAVE_USER_DATA';
export const SAVE_PROFILE = 'SAVE_PROFILE';
export const SAVE_PHONE = 'SAVE_PHONE';

// - Catalogues
export const SAVE_CATALOGUES = 'SAVE_CATALOGUES';
export const SAVE_SUBCATEGORIES = 'SAVE_SUBCATEGORIES';

// - Products
export const SAVE_PRODUCTS = 'SAVE_PRODUCTS';

// - Loading
export const SET_LOADING_TRUE = 'SET_LOADING_TRUE';
export const SET_LOADING_FALSE = 'SET_LOADING_FALSE';

// - Guest
export const SET_GUEST_TRUE = 'SET_GUEST_TRUE';
export const SET_GUEST_FALSE = 'SET_GUEST_FALSE';

// - ISPAYMENT
export const SET_PAYMENT_TRUE = 'SET_PAYMENT_TRUE';
export const SET_PAYMENT_FALSE = 'SET_PAYMENT_FALSE';

// - Order
export const SAVE_ORDERS = 'SAVE_ORDERS';

// - Welcome Seen
export const SET_WELCOME = 'SET_WELCOME';

// - Category
export const SET_CATEGORY = 'SET_CATEGORY';
export const CLEAR_CATEGORY = 'CLEAR_CATEGORY';
export const SAVE_CATEGORIES = 'SAVE_CATEGORIES';
export const CLEAR_CATEGORIES = 'CLEAR_CATEGORIES';

// - SubCategory
export const SET_SUBCATEGORY = 'SET_SUBCATEGORY';
export const CLEAR_SUBCATEGORY = 'CLEAR_SUBCATEGORY';

